name = "finance_mcp"
description = ""
version = "0.1.0-dev"

authors = ["Sergei Adonev"]
maintainers = ["Sergei Adonev <admin@punks.work>"]
maintainers-logins = ["PWOAdmin"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
aws = "^25.2.0"

[[depends-on]]
gnatcoll = "^25.0.0"
